### ISSUE TITLE
bug ilidan achievement

### ISSUE THREAD

**Issue by frujinavlad** [rosedu/wouso#263]
am avut ieri 5 vraji pe mine si nu am primit ilidan. in plus imi aparea la Magie cu rosu +1 ca si cum ar fi mesaj nou si nu aveam nimic si nu disparea. la fel am si acum de altfel acel +1, insa vrajile nu le mai am dar nici medalia... totusi am folosit destul de mult gold sa primesc medalia si inca nu o am... Este bug??

De asemenea am activat disguise +25% si am facut 19000 de puncte si nu mai imi aparea la corabie nicio culoare... Este vreun bug ceva??

**Comment by palcu** [comment]
Merge
