### ISSUE TITLE
Staff member can't access Specialquest link and Quest link, though links are present in the Control Panel interface

### ISSUE THREAD

**Issue by razvand** [rosedu/wouso#476]
A Staff (non-admin) member can use the sidebar of the Control Panel interface to access the "Specialquest" and "Quest" links. However, they end up pointing him to a login screen. I assume such a user doesn't have permissions to access these features. In which case, the links should not be there. All links in the sidebar should be links the user is able to access.

**Comment by ovidiu-giorgi** [comment]
Working on this.
