### ISSUE TITLE
Add possibility of uploading an images for questions and answers

### ISSUE THREAD

**Issue by razvand** [rosedu/wouso#584]
Both question text and aswer text should allow the addition of an image to it. Thee should happen in the add forms for the editor (https://github.com/rosedu/wouso/blob/master/wouso/resources/templates/cpanel/add_answer.html, https://github.com/rosedu/wouso/blob/master/wouso/resources/templates/cpanel/qpool_new.html) and in the question print form for the user (https://github.com/rosedu/wouso/blob/master/wouso/games/challenge/templates/challenge/challenge.html)

**Comment by iulianR** [comment]
Implemented on the development branch https://github.com/iulianR/wouso/commit/2b8226fb521734780fa36e58d2771b8e00d0907d. Will merge it to master soon.
