### ISSUE TITLE
No help pop-up for the "CHALLENGE!" and "REPORT" buttons

### ISSUE THREAD

**Issue by razvand** [rosedu/wouso#608]
When hovering over the "CHALLENGE!" and "REPORT" buttons there is no help pop-up. Please add one for consistency. The help pop-up should say:
* "Challenge this player; answer questions in a given time"
* "Report this player to the game administators"

Also, please remove the exclamation mark from the "CHALLENGE!" name of the button.

**Comment by andreibotila** [comment]
@razvand  Where can i find the REPORT buton ? WoUSO is over so i can't enter the site. Also the "CHALLENGE!" is written "Challenge!", am i right ?
