### ISSUE TITLE
Write regression test for bug when removing an user from a special group

### ISSUE THREAD

**Issue by palcu** [rosedu/wouso#636]
In issue https://github.com/rosedu/wouso/issues/574 and pull request https://github.com/rosedu/wouso/pull/627 @jercaianu fixed a bug, but he did not found time to write a regression test for that bug.

The test should go into `wouso/games/specialquest/tests.py` and the skeleton for it is:

```py
class SpecialQuestGroupTest(TestCase):
    def setUp(self):
        """Set up stuff..."""
        pass

    def test_remove_user(self):
        pass
```

Closes #574.

**Comment by andreibotila** [comment]
@iulianR I have a question, in examples i've seen with "def setUp" there is no "pass", setUp they used to setup things required beforehand. Any tip on what i should google is welcomed.

**Comment by palcu** [comment]
@andreibotila the `pass` thingy is just there because I wrote a stub method. You should remove it and write the actual code.
