### ISSUE TITLE
 No module named django_bootstrap_breadcrumbs

### ISSUE THREAD

**Issue by segmentationfaulter** [rosedu/wouso#643]
When I run ./manage.py with whatever the arguments, I get the error

Error: No module named django_bootstrap_breadcrumbs

where is the problem?

**Comment by iulianR** [comment]
@segmentationfaulter Have you managed to fix the problem?

**Comment by segmentationfaulter** [comment]
@iulianR sorry man, I could not try, I've moved to Debian from Ubuntu, the error I was getting when I was on Ubuntu, I will try it on Debian and will let you know. Thank you

**Comment by razvand** [comment]
@segmentationfaulter, the error seems to be caused by a missing `libssl-dev` package. I've updated the [README file](https://github.com/rosedu/wouso/blob/master/README.md) with this, as show in #646.
