### ISSUE TITLE
Not all tables are created on syncdb

### ISSUE THREAD

**Issue by iulianR** [rosedu/wouso#663]
After doing a fresh install, when trying to run ```python manage.py syncdb```, not all tables seems to be created. Last table is always ```specialchallenge_specialchallenge``` which I think is just before ```south_migrationhistory``` (just an assumption). After that, ```python manage.py createsuperuser``` gets called but fails because the ```user_player``` table was not created. Same thing happens when doing ```python manage.py wousoctl --setup``` (syncdb gets called there as well).

@razvand found an workaround:
- remove ```south``` from ```INSTALLED_APPS``` in ```settings.py```
- run ```syncdb```
- add ```south``` back
- run ```syncdb``` again.

Full traceback here:
http://pastebin.com/mDHgA7Ja

@alexef @mihneadb Any ideas?

**Comment by iulianR** [comment]
Pinging @alexef @mihneadb @razvand.
It would be great if we could solve this until tommorrow :) - ROSEdu Challenge Hackaton v2

**Comment by razvand** [comment]
I'll take a look in the evening. I know I struggled a bit with that and found no solution. I will check it out again.

**Comment by mihneadb** [comment]
I don't have an idea, that's why I didn't reply in the first place. :(

On Fri, Feb 27, 2015 at 3:10 PM, Iulian Gabriel Radu <
notifications@github.com> wrote:

> Pinging @alexef <https://github.com/alexef> @mihneadb
> <https://github.com/mihneadb> @razvand <https://github.com/razvand>.
> It would be great if we could solve this until tommorrow :) - ROSEdu
> Challenge Hackaton v2
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/rosedu/wouso/issues/663#issuecomment-76391808>.
>



-- 
Mihnea Dobrescu-Balaur

**Comment by palcu** [comment]
Did a little research and if I run `./manage.py syncdb --all` and then `./manage.py migrate --fake` it works. From this [tip](https://stackoverflow.com/questions/10834237/django-syncdb-and-migrate). But we should [investigate](https://stackoverflow.com/questions/24569925/clarification-on-django-syncdb-all-option?rq=1) more if the migrations to south were properly executed.

**Comment by palcu** [comment]
I think this should fix it. https://github.com/rosedu/wouso/pull/700/files
