### ISSUE TITLE
Lesson tag and category names should be unique

### ISSUE THREAD

**Issue by iulianR** [rosedu/wouso#673]
### Problem
- Multiple lesson categories with the same name can exist
- Multiple lesson tags with the same name can exist

### Solution
- Make lesson category name unique
- Make lesson tag name unique

**Comment by Gabriel93** [comment]
I will work on this issue.

**Comment by palcu** [comment]
You should also:

* generate a migration
* write a test

When you write the test, you can use the `raises` [decorator](https://nose.readthedocs.org/en/latest/testing_tools.html).

**Comment by palcu** [comment]
You can generate a migration `./manage.py schemamigration <app> <migration_name> --auto`

**Comment by palcu** [comment]
Example of the test:

```py
from nose.tools import raises
from django.db import IntegrityError
class MyModelTestCase(TestCase):
    
@raises(IntegrityError)
    def test_category_name_is_unique(self):
        category1 = MyObject.objects.create(name='a')
        category2 = MyObject.objects.create(name='a')
        category1.save()
        category2.save()
```
