### ISSUE TITLE
Glyphicons should be placed before the name of the button

### ISSUE THREAD

**Issue by iulianR** [rosedu/wouso#675]
### Problem
- On the formulas page, the icon for edit is placed after the name of the button.

### Solution
- Place the icon before the button

Also check if the same problem appears in other places.

**Comment by AlexandruGhergut** [comment]
I will attempt to fix this.

**Comment by mariuscoto** [comment]
Great work @AlexandruGhergut ! Also join [ROSEdu Challenge](http://challenge.rosedu.org/challenges/ROSEduChallenge) and you can win great prizes for your contribution!
