### ISSUE TITLE
Rename 'Back to list' button

### ISSUE THREAD

**Issue by gabrielivascu** [rosedu/wouso#676]
<h3>Problem</h3>
On CPanel manage player page 'Back to list' button should be renamed to 'Cancel' for consistency with other pages. It should also have yellow color.
<h3>Solution</h3>
Check other pages such as manage forum categories for similarity.

**Comment by psilvia** [comment]
I'm trying to work on this issue.

**Comment by Marian25** [comment]
I want to work on this issue.
