### ISSUE TITLE
Add formula form misses 'Cancel' and 'Reset' buttons

### ISSUE THREAD

**Issue by gabrielivascu** [rosedu/wouso#678]
<h3>Problem</h3>
The form in CPanel add formula page lacks buttons for cancel and reset. They should be added.
<h3>Solution</h3>
Check other pages such as edit formula for similarity.

**Comment by Marian25** [comment]
I want to work on this issue.

**Comment by mariuscoto** [comment]
Great work @Marian25 ! Also join [ROSEdu Challenge](http://challenge.rosedu.org/challenges/ROSEduChallenge) and you can win great prizes for your contribution!
