### ISSUE TITLE
[Hackaton] Configurare WoUSO

### ISSUE THREAD

**Issue by gabrielivascu** [rosedu/wouso#680]
La pasul 8:
1. În fișierul ```settings.py``` comentați linia ```'south'``` (folosind ```#```)
2. În fișierul ```wousoctl.py``` din ```core/game/management/commands/``` comentați linia ```'call_command('migrate')``` (folosind ```#```)
3. În directorul ```wouso``` rulați comanda ```./manage.py wousoctl --setup``` (creați și un user când sunteți întrebați)
4. Decomentați cele două linii de la primii 2 pași
5. În directorul ```wouso```rulați comanda ```./manage.py  syncdb```
6. În directorul ```wouso```rulați comanda ```./manage.py  migrate --fake```

**Comment by iulianR** [comment]
Fixed in #700
