### ISSUE TITLE
[Files] Missing 'Cancel' and 'Reset' buttons

### ISSUE THREAD

**Issue by gabrielivascu** [rosedu/wouso#692]
<h3>Problem</h3>
The form in CPanel - files - add/edit category lacks buttons for cancel and reset. They should be added for consistency with other add/edit pages such as quiz, lessons etc
<h3>Hint</h3>
Check the form in <code>interface/apps/files/templates/files/cpanel/category.html</code>

**Comment by AdriSal** [comment]
I'm working on this.
