### ISSUE TITLE
teamquest: Add summary of points awarded for a given level in the Team Quest

### ISSUE THREAD

**Issue by razvand** [rosedu/wouso#729]
Each level tab in the the team quest interface should show a summary of points awarded. It should show:
* the number of points awarded so far for the given level (sum of points awarded for level questions and possibly bonuses)
* in case of a bonus and if the team finished the quest, the bonus obtained
* (nice to have, if not that difficult to implement) in case the team finished the test, the position in the number of teams that completed the level

**Comment by razvan3895** [comment]
Fixed.
