### ISSUE TITLE
teamquest: Do not show bonus pop-up messages in case their is no bonus for the quest

### ISSUE THREAD

**Issue by razvand** [rosedu/wouso#731]
If one creates a quest without bonus points (`0` bonus points) and a player completes a level in the quest, the following message below is shown as a pop-up message: _For being the first to complete this level, your team is awarded 0 points._

This message shouldn't be shown in this case. There is no use in printing a message that tells _your team is awarded 0 points_.

**Comment by razvan3895** [comment]
Fixed.
