### ISSUE TITLE
level up - gold problem

### ISSUE THREAD

**Issue by cristiannancu** [rosedu/wouso#770]
Am si eu o problema legata de LVL-UP. Am facut level 2 si am primit cei 20 gold, apoi cumva am facut downgrade la level 1 si mi s-au scazut cei 20 gold. Acum sunt iar level 2 (1020p) dar am 0 gold. 

Cred ca motivul pt downgrade a fost lansarea unui challenge (-30p). De atunci pana in prezent am raspuns gresit la qotd si am castigat un challenge.

Cristian-Ionut NANCU
Vratmel, CD

**Comment by iulianR** [comment]
Am reușit să reproducem problema. Revenim cu un fix cât mai repede posibil.

**Comment by razvanch** [comment]
@cristiannancu, pentru ca ai reportat bug-ul o sa primesti un bonus in gold. Pe langa asta vei primi si cei 20 de gold pierduti, dupa ce rezolvam bug-ul.

**Comment by PopAdi** [comment]
Aceeasi problema am intampinat-o si eu: http://i.imgur.com/46kaGzI.jpg

**Comment by razvanch** [comment]
Maine in jur de 12 ar trebui sa fie reparat.

**Comment by iulianR** [comment]
Fixed in #773. Will take effect later tonight.
