### ISSUE TITLE
All questions answered corectly but no 500 points

### ISSUE THREAD

**Issue by PopAdi** [rosedu/wouso#772]
Just finished a challenge and even I answered all questions corectly in under a minute, I've got only 475 / 500. Pastebin (ctrl+c, ctrl+v) => http://pastiebin.com/562810cb6847a
+ 2 screenshots

![screenshot from 2015-10-22 01 21 58](https://cloud.githubusercontent.com/assets/15239096/10651982/8237d01a-785b-11e5-85a9-cce98d9bb299.png)
![screenshot from 2015-10-22 01 22 06](https://cloud.githubusercontent.com/assets/15239096/10651983/82521790-785b-11e5-8075-d56f62a41142.png)

**Comment by gabrielivascu** [comment]
You marked one extra answer in the second question, that's why you didn't get 500 :)

**Comment by PopAdi** [comment]
Lol, my bad. You can delete this.
