### ISSUE TITLE
Visual glitch in CPanel

### ISSUE THREAD

**Issue by iulianR** [rosedu/wouso#774]
There's a small problem with the panels on the right side of the Status page on CPanel, as seen below. Investigate and fix.
![screenshot from 2015-10-22 15-27-53](https://cloud.githubusercontent.com/assets/6775259/10665122/88c5169c-78d1-11e5-9333-09532e1a92fc.png)

**Comment by DianaDespa** [comment]
Working on it :)

**Comment by razvanch** [comment]
Fixed in #799
