### ISSUE TITLE
Check, fix and test achievements

### ISSUE THREAD

**Issue by iulianR** [rosedu/wouso#780]
In the interface/activity directory you can find the achievements.py file which contains a list of all possible achievements. Choose one achievement and write test for it. If it doesn't work correctly, fix it.

Please type the achievement name here if you are currently working on one.

**Comment by iulianR** [comment]
Fixed:
- [x] ach-early-bird - #822 
- [x] ach-night-owl - #822

**Comment by ArmandNM** [comment]
Working on this.

**Comment by palcu** [comment]
Everything is tested here.
