### ISSUE TITLE
Wrong challenges statistic details

### ISSUE THREAD

**Issue by PopAdi** [rosedu/wouso#781]
When you are on your challenge statistic page and you click on Details, there is a high chance of not getting the expected result. Instead, there is another player name (not the one you challenged) and no details about points, score etc.

Update: from 13 challenges, 4 of them show bad details.

![1](https://cloud.githubusercontent.com/assets/15239096/10701122/c6c4c7a4-79ca-11e5-9bf7-b862f5c18319.png)
![2](https://cloud.githubusercontent.com/assets/15239096/10701123/c6de7e10-79ca-11e5-9bc9-cecb7962989f.png)

**Comment by razvanch** [comment]
Fixed.
