### ISSUE TITLE
Test challenges appears in homepage

### ISSUE THREAD

**Issue by palcu** [rosedu/wouso#795]
If I have the challenge option in game activated in the settings module, then I should see the button.

Look over this [file](https://github.com/rosedu/wouso/blob/master/wouso/interface/tests.py) for an example.

![screenshot 2015-10-23 22 44 40](https://cloud.githubusercontent.com/assets/772220/10703298/b61c776e-79d7-11e5-9e6d-93f2bbcb1595.png)

**Comment by CosGamer** [comment]
Working on it

**Comment by dosarudaniel** [comment]
Works now?

**Comment by palcu** [comment]
Maybe it's because of the theme
