### ISSUE TITLE
Double gold received

### ISSUE THREAD

**Issue by PopAdi** [rosedu/wouso#818]
As you can see in the screenshot, this player (and maybe others) got double gold from leveling up. I talked with him and he said he really has 40 gold and that I can report the bug. Have a nice day!

![screenshot from 2015-10-24 11 14 17](https://cloud.githubusercontent.com/assets/15239096/10709746/5e068c5c-7a42-11e5-9d64-cb7cc54b376f.png)

**Comment by iulianR** [comment]
@razvanch You recently looked into the level upgrade problems. Can you have a look?

**Comment by PopAdi** [comment]
Another one, just a couple of minutes ago (if it helps).
![screenshot_2015-10-24-18-34-24](https://cloud.githubusercontent.com/assets/15239096/10711267/664bee8e-7a7e-11e5-84f2-c7059f5daa8f.png)

**Comment by iulianR** [comment]
It seems that we forgot to apply @razvanch's bug fix that dealt with the level upgrade/downgrade problem. We did it now so hopefully everything will be ok from now on.

@PopAdi Thanks for your detective work. I rewarded you accordingly with gold in-game. Keep up the good work and let us know if you notice any more problems.
