### ISSUE TITLE
Morpheus achievement 

### ISSUE THREAD

**Issue by PopAdi** [rosedu/wouso#819]
Hi!
There seems to be a problem with the "Morpheus" achievement. => Morpheus - Login between 3-5 AM for 3 days (not in a row) (0). I logged in for more than 3 days in the specified interval, but I did not received the badge. Can you check? Thanks and...
Have a nice day!

**Comment by iulianR** [comment]
There was indeed a bug. Fixed it in #822. Will have effect starting later tonight.

@PopAdi I also gave you the achievement. If you want to contribute even more towards a bug-free game, feel free to install the project and write some code. We'll be more than glad to help you out with your first contributions
