### ISSUE TITLE
10 won challenges in a row - no achievement

### ISSUE THREAD

**Issue by PopAdi** [rosedu/wouso#826]
I won over 10 challenges in a row, but I did not receive the achievement => "Hercules - Win 10 challenges in a row". I think there must be a problem with it.
Have a nice evening!

![screenshot from 2015-10-28 23 54 12](https://cloud.githubusercontent.com/assets/15239096/10804468/4f8cab16-7dd0-11e5-83ca-97d343d1adfc.png)

**Comment by PopAdi** [comment]
I guess this issue can be closed, I received my achievement (maybe it was a delay in the game).

**Comment by palcu** [comment]
There is a delay of an hour for all the achievements. We run a cron job every hour to check if new achievements have been made.
