### ISSUE TITLE
Draw result or expired challenges

### ISSUE THREAD

**Issue by PopAdi** [rosedu/wouso#828]
Hi!
I don't know if this is how the game is supposed to work, but I think there might be 2 problems:
- for a draw result in a challenge, the challenge it's marked as lost
- for an expired challenge, it is marked as lost as well
- [a refused (not expired) challenge is marked as lost as well, but maybe this is ok]

I experienced the first problem a few minutes ago. I had 5 lost challenges and I challenged a player. We both scored 500 points, resulting in a draw but...surprise, now I have 6 lost challenges.

I checked my entire game history and I made a text document, available here => http://pastebin.com/nJmxaAas

I have 23 won challenges, 3 lost, 2 expired and 1 draw. In the challenge top I appear to have 23 won challenges and 6 lost challenges, so yeah, the expired and the draw ones are marked as lost.

Have a nice evening!

**Comment by iulianR** [comment]
Fixed in #830
