### ISSUE TITLE
Sender and receiver messages in Django Admin

### ISSUE THREAD

**Issue by palcu** [rosedu/wouso#832]
It would be nice if the real names appeared. Relevant screenshot:

![screenshot 2015-11-01 23 40 10](https://cloud.githubusercontent.com/assets/772220/10871513/031be8f8-80f2-11e5-8b5a-f4992d626b2f.png)

**Comment by ICalofir** [comment]
Working on this.

**Comment by iulianR** [comment]
Fixed in #866
