### ISSUE TITLE
Add/edit news item textbox

### ISSUE THREAD

**Issue by palcu** [rosedu/wouso#834]
The content should be a text box.
![screenshot 2015-11-02 00 26 31](https://cloud.githubusercontent.com/assets/772220/10871755/81f287a8-80f8-11e5-85f1-af8bdb99fd98.png)

**Comment by NarcisaAM** [comment]
Working on this.

**Comment by NarcisaAM** [comment]
Fixed in #852

**Comment by palcu** [comment]
Done https://github.com/rosedu/wouso/pull/852
