### ISSUE TITLE
Hide exchange form if exchange option is disabled

### ISSUE THREAD

**Issue by gabrielivascu** [rosedu/wouso#851]
I find the current behavior pretty odd: if Bazaar Exchange is disabled then an error message saying 'Exchange is disabled' is displayed for the user when he tries to make an exchange.

I think it would make more sense to have the message displayed on the Magic -> Exchange page and have the form hidden if this option is disabled.

**Comment by damianr13** [comment]
incerc eu sa rezolv asta

**Comment by damianr13** [comment]
am terminat
