### ISSUE TITLE
Change contact page info

### ISSUE THREAD

**Issue by victor-ciurel** [rosedu/wouso#905]
Change contact page info to:

- WoUSO facebook page
- wouso@rosedu.org
- github wouso repo

Also translate to Romanian.

![screenshot from 2017-10-10 21-51-17](https://user-images.githubusercontent.com/3243689/31404613-339c4cec-ae05-11e7-8f67-0cafe9188787.png)

**Comment by iulianR** [comment]
Contact page is a static page. Static pages can be edited in Control Panel -> Configuration -> Static pages.

**Comment by victor-ciurel** [comment]
Fixed it from static pages in the control panel.
