### ISSUE TITLE
Timer on challenges appears on a white text on white background

### ISSUE THREAD

**Issue by victor-ciurel** [rosedu/wouso#913]
Timer is hard to read in a challenge. There should be contrast for it (black text on white background maybe). This bug may be present in more "popup" boxes (I remember I got one from a message doing something for the special quest).

**Comment by iulianR** [comment]
@ruxandraS can you have a look? This might only be a problem with the current theme.

**Comment by ruxandraS** [comment]
@iulianR c943a93 from wouso-extras repo should fix this
